### ISSUE TITLE
刷流插件报错

### ISSUE THREAD

**Issue by shixiaolong777** [jxxghp/MoviePilot-Plugins#117]
ERROR:   scheduler.py - 定时任务 subscribe_refresh 执行失败：unsupported operand type(s) for /: 'str' and 'int' - Traceback (most recent call last):
  File "/app/app/scheduler.py", line 279, in start
    job["func"](*args, **kwargs)
  File "/app/app/chain/subscribe.py", line 422, in refresh
    self.match(
  File "/app/app/chain/subscribe.py", line 688, in match
    if not self.torrenthelper.filter_torrent(torrent_info=torrent_info,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/helper/torrent.py", line 391, in filter_torrent
    if not (begin_size * 1024 ** 3 <= (torrent_info.size / episodes_num) <= end_size * 1024 ** 3):
                                       ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'int'

**Comment by jxxghp** [comment]
@shixiaolong777 大小过滤你填的不是数字？

**Comment by shixiaolong777** [comment]
![Uploading 屏幕截图 2024-03-24 100210.png…]()

**Comment by shixiaolong777** [comment]
![屏幕截图 2024-03-24 100210](https://github.com/jxxghp/MoviePilot-Plugins/assets/74590603/8ac12030-9680-46da-83ac-3af6d564e660)

**Comment by jxxghp** [comment]
是刷的馒头吗？

**Comment by shixiaolong777** [comment]
不是，观众

**Comment by jxxghp** [comment]
你的订阅默认过滤规则也贴下看看

**Comment by shixiaolong777** [comment]
就是一个4k，一个1080p

**Comment by shixiaolong777** [comment]
还有个问题，就是不管我保种体积设置多少，都说超过保种体积，实际上一个都没有
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/74590603/2a39ff16-a2dc-432c-ae05-a29c1b9f9b91)
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/74590603/193f7cad-a3fa-416b-bb99-c4941631e320)

**Comment by shixiaolong777** [comment]
重新安装插件，好像又好了
