### ISSUE TITLE
pushdeer 安装失败

### ISSUE THREAD

**Issue by GateCross** [jxxghp/MoviePilot-Plugins#198]
ModuleNotFoundError: No module named 'pypushdeer'
    from pypushdeer import PushDeer
  File "/app/app/plugins/pushdeermsg/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    module = importlib.import_module(full_package_name)
  File "/app/app/helper/module.py", line 31, in load
【ERROR】2024-04-11 15:37:09,644 - module.py - 加载模块 pushdeermsg 失败：No module named 'pypushdeer' - Traceback (most recent call last):

**Comment by GateCross** [comment]
使用代理后安装成功
