### ISSUE TITLE
清理QB无效做种插件配置页空白

### ISSUE THREAD

**Issue by CookieJaySJ** [jxxghp/MoviePilot-Plugins#295]
如图所示，无配置页面 
@DzAvril @jxxghp 麻烦大佬们看看啥bug
<img width="1031" alt="image" src="https://github.com/jxxghp/MoviePilot-Plugins/assets/10297471/15ca5a71-04b7-4567-8dc6-474215f24112">

**Comment by DzAvril** [comment]
@CookieJaySJ 我这边好的，重启一下 mp 看看，还是有问题贴一下插件日志

**Comment by dlovew** [comment]
同样空白

**Comment by AisukaYuki** [comment]
```ERROR:   plugin.py - 加载插件 CleanInvalidSeed 出错：'CleanInvalidSeed' object has no attribute '_onlyonce' - Traceback (most recent call last):
  File "\App\MoviePilot\MoviePilot-Backend\app\core\plugin.py", line 155, in start
    plugin_obj.init_plugin(self.get_plugin_config(plugin_id))
  File "\App\MoviePilot\MoviePilot-Backend\app\plugins\cleaninvalidseed\__init__.py", line 69, in init_plugin
    if self._onlyonce:
       ^^^^^^^^^^^^^^
AttributeError: 'CleanInvalidSeed' object has no attribute '_onlyonce'
```
